/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Dark Zone (Hero)
        'space-black': '#000000',
        'star-gold': '#D4A853',
        'star-gold-dim': '#8B7355',
        'node-red': '#FF6B6B',
        'node-cyan': '#4ECDC4',
        'node-green': '#44AA44',
        'node-magenta': '#C44EC4',
        'node-orange': '#FF8C42',
        'node-blue': '#4488FF',
        'node-yellow': '#FFD93D',
        'node-teal': '#2DD4BF',
        'node-purple': '#A855F7',
        'filament-warm': 'rgba(212, 168, 83, 0.25)',
        'filament-cool': 'rgba(180, 200, 255, 0.15)',
        'stardust': 'rgba(255, 255, 255, 0.03)',
        'text-primary-dark': '#FFFFFF',
        'text-secondary-dark': 'rgba(255, 255, 255, 0.65)',
        // Light Zone (Analysis)
        'off-white': '#FAF9F6',
        'warm-gray': '#F0EDE8',
        'surface-white': '#FFFFFF',
        'surface-elevated': '#F5F3EF',
        'text-primary': '#1A1B3A',
        'text-secondary': '#5A5C7A',
        'text-tertiary': '#8B8DA3',
        'accent-indigo': '#1A1B3A',
        'accent-indigo-light': '#2E2F5A',
        'accent-gold': '#D4A853',
        'accent-gold-light': '#F0E2C0',
        'border-light': '#E5E2DC',
        'border-medium': '#D0CCC4',
        'success': '#22A559',
        'warning': '#E8A820',
        'danger': '#D94040',
        'info': '#3B6FC4',
        // Shadcn compat
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        serif: ['"Source Serif Pro"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', '"Courier New"', 'monospace'],
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'space-16': '64px',
        'space-20': '80px',
        'space-24': '96px',
        'space-32': '128px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: "0 1px 3px rgba(26, 27, 58, 0.04)",
        'card-hover': "0 4px 12px rgba(26, 27, 58, 0.08)",
        tooltip: "0 4px 16px rgba(0, 0, 0, 0.12)",
        modal: "0 20px 60px rgba(0, 0, 0, 0.15)",
      },
      zIndex: {
        'bg': '-1',
        'content': '1',
        'elevated': '10',
        'sticky-nav': '50',
        'modal': '100',
        'toast': '200',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "bounce-chevron": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(8px)" },
        },
        "fadeIn": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "bounce-chevron": "bounce-chevron 1.5s ease-in-out infinite",
        "fadeIn": "fadeIn 0.2s ease-out",
      },
      maxWidth: {
        'container': '1400px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
